### ISSUE TITLE
Doubt in the math to calculate the `poolTokensToDeposit` in the `deposit()` function

### ISSUE THREAD

**Issue by alfheimrShiven** [Cyfrin/5-t-swap-audit#5]
According to the comments, the math explanation considers this invariant to hold:

```
 // Our invariant says weth, poolTokens, and liquidity tokens must always have the same ratio after the
            // initial deposit
            // poolTokens / constant(k) = weth
            // weth / constant(k) = liquidityTokens
            // aka...
            // weth / poolTokens = constant(k)
```
Refer code: https://github.com/Cyfrin/5-t-swap-audit/blob/main/src/TSwapPool.sol#L132

But for a constant product AMM, the invariant formula is
`poolTokens * wEth = constant(k)`

Then why is `poolTokens / constant(k) = weth` being used?

This being said, the formula for calculating `poolTokenToDeposit` is correct in the `getPoolTokensToDepositBasedOnWeth()`
https://github.com/Cyfrin/5-t-swap-audit/blob/main/src/TSwapPool.sol#L429

The comment I pointed out seems a bit confusing/contradicting to what is actually being used in `getPoolTokensToDepositBasedOnWeth()`.

**Comment by alfheimrShiven** [comment]
Sorry I understood why `poolTokens / constant(k) = weth` is considered. It's the deposit ratio that should hold. Refer image for detailed math.
![deposit math](https://github.com/Cyfrin/5-t-swap-audit/assets/50408041/f0f67458-9c88-407d-a441-7d883c578b29)

**Comment by PatrickAlphaC** [comment]
Wow, sorry I totally missed this. So you're good now?

**Comment by alfheimrShiven** [comment]
@PatrickAlphaC yes! Thanks.
