### ISSUE TITLE
testing errors 

### ISSUE THREAD

**Issue by monaldmuck** [Cyfrin/5-t-swap-audit#6]
when i use :pragma solidity 0.8.20; i get 
Source file requires different compiler version (current compiler is 0.8.19+commit.7dd6d404.Emscripten.clang) - note that nightly builds are considered to be strictly less than the released version

when i change to: pragma solidity >=0.8.19 <0.9.0;

i get an error with my:  import {Test} from "forge-std/Test.sol";
Source "forge-std/Test.sol" not found: File import callback not supported

please help

**Comment by ShivamDeshmukh21** [comment]
> i get an error with my: import {Test} from "forge-std/Test.sol"; Source "forge-std/Test.sol" not found: File import callback not supported

You will have to manually add the `forge-std` directory to `foundry.toml` like so:
```
remappings = [
    // other imports,
    'forge-std=lib/forge-std/src'
]
```

**Comment by PatrickAlphaC** [comment]
Going to close, looks like you're all set?
